### ISSUE TITLE
"compileSdkVersion is not specified" after updating to 0.2.0

### ISSUE THREAD

**Issue by frangipanes** [tynn-xyz/BuildSrc#3]
Following the fix for #1 , I updated my Android Library project to use plugin 0.2.0 (previously 1.2.0). I also updated the dokka plugin to 1.4.30 (up from 0.10.1). However, I now encounter the following error with evaluating the gradle build:

```
A problem occurred configuring project ':AndroidSDK'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle
...
Caused by: com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle
        at com.android.builder.errors.IssueReporter.reportError(IssueReporter.kt:107)
        at com.android.builder.errors.IssueReporter.reportError$default(IssueReporter.kt:103)
        at com.android.builder.errors.IssueReporter.reportError(IssueReporter.kt)
        at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:69)
        ... 179 more
```

This happens even if I remove all of the configuration for tynn-xyz (the stuff like this):
```
if (it.name =~ /.*Kdoc$/) {
        it.configure {
            configuration {
...
```
and even if I leave the dokka plugin at 0.10.1.

**Comment by tynn** [comment]
Could you provide access to your failing project or add a test case for it in https://github.com/tynn-xyz/BuildSrc/blob/main/publishing/src/test/groovy/xyz/tynn/buildsrc/publishing/AndroidKdocPluginFuncTest.groovy?

It might be related to the _Android Gradle Plugin_ upgrade. Did you define `compileSdkVersion` or `compileSdk` within your `android { ... }` configurations?
